version: "3"

services:
  itemsdb:
    image: postgres
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
    - "5432:5432"
    networks:
    - itemservice
    volumes:
    - "pgdata:/var/lib/postgresql/data"
    environment:
    - POSTGRES_PASSWORD=items
    - POSTGRES_USER=items
    - POSTGRES_DB=items

  itemservice:
    image: sobkowiak/itemservice:latest
    ports:
    - "8090:8090"
    networks:
    - itemservice
    depends_on:
    - itemsdb
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "1"
          memory: 500M

volumes:
  pgdata:

networks:
  itemservice: